---
title: "R Notebook"
output: html_document
---

```{r,echo=FALSE}
source("source_files/diag_bin.R")
source("source_files/envel_bin.R")
source("source_files/gml_tests.R")
```


# Reading etc
```{r}
sem <- read.table("~/a_link_to_papers/*2017-1/Categorical/caio_2017/sementes.dat")
names(sem) = c("Temperatura","Nivel_Umidade","Temp_Umidade","N_de_sementes")
sem$Nivel_Umidade <- gsub("m\xe9dio","medio",sem$Nivel_Umidade)

for(i in 1:3) sem[,i] <- as.factor(sem[,i])
sapply(sem,class)

print(sem)
m=rep(100,18)
```

# Fit

## Interacaao Tripla

```{r fit}
sem_binfit_3ordem <- glm(cbind(sem$N_de_sementes,100-sem$N_de_sementes)~ Nivel_Umidade*Temp_Umidade + Temperatura*Nivel_Umidade + Temperatura*Temp_Umidade + Temperatura*Temp_Umidade*Nivel_Umidade,sem,family = binomial())
summary(sem_binfit_3ordem)
```
### CBeta_tripla
```{r}
m.C_3ordem = matrix(c(numeric(14),1,rep(c(numeric(18),1),3)),4,18,byrow = TRUE)
v.M_3ordem = c(numeric(4))
testeF.CBM.MLG(sem_binfit_3ordem,m.C_3ordem,v.M_3ordem)
```


## Modelo2 sem interacao tripla
```{r}
sem_binfit_mod2 <- glm(cbind(sem$N_de_sementes,100-sem$N_de_sementes)~ Nivel_Umidade*Temp_Umidade + Temperatura*Nivel_Umidade + Temperatura*Temp_Umidade,sem,family = binomial())
summary(sem_binfit_mod2)
```
### Cbeta p/ testar interacao dos $\alpha$
```{r}
m.C_mod2 <- cbind(matrix(numeric(10*4),nrow = 4),diag(4))
v.M_mod2 = c(numeric(4))
testeF.CBM.MLG(sem_binfit_mod2,m.C_mod2,v.M_mod2)
```
### Envelopes para sem interacao tripla
```{r}
diagBern(sem_binfit_mod2)
envelBinom(sem_binfit_mod2,"logit")
```

## Modelo3 sem interacao dos $\alpha$
```{r}
sem_binfit_mod3 <- glm(cbind(sem$N_de_sementes,100-sem$N_de_sementes)~ Nivel_Umidade*Temp_Umidade + Temperatura,sem,family = binomial())
summary(sem_binfit_mod3)
```
### Envelopes para Modelo3 sem interacao dos $\alpha$
```{r}
diagBern(sem_binfit_mod3)
envelBinom(sem_binfit_mod3,"logit")
```

